/home/dg9272/.conda/envs/cos485/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['split_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(split_batches=False)
  warnings.warn(
Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Instantiating the dataset and dataloader...
Checking the dataset and dataloader...
person_images: torch.Size([32, 3, 96, 96])
ca_images: torch.Size([32, 3, 96, 96])
garment_images: torch.Size([32, 3, 96, 96])
person_poses: torch.Size([32, 25, 2])
garment_poses: torch.Size([32, 1, 2])
Instantiating U-Nets...
((96, 96),)
Instantiating the trainer...
Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

Loading model checkpoint from /scratch/network/dg9272/cos485/checkpoints/checks4/checkpoint.20200.pt
Loading optimizer and scaler...
checkpoint loaded from /scratch/network/dg9272/cos485/checkpoints/checks4/checkpoint.20200.pt
Starting sampling loop...
Traceback (most recent call last):
  File "/home/dg9272/tryondiffusion2.0/test.py", line 153, in <module>
    main()
  File "/home/dg9272/tryondiffusion2.0/test.py", line 142, in main
    images = trainer.sample(**imagen_sample_kwargs)  # returns List[Image]
  File "/home/dg9272/.conda/envs/cos485/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dg9272/tryondiffusion2.0/tryondiffusion/common/torch_helpers.py", line 63, in inner
    out = fn(model, *args, **kwargs)
  File "/home/dg9272/tryondiffusion2.0/tryondiffusion/tryon_imagen_trainer.py", line 797, in sample
    output = self.imagen.sample(*args, device=self.device, **kwargs)
  File "/home/dg9272/.conda/envs/cos485/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dg9272/tryondiffusion2.0/tryondiffusion/common/torch_helpers.py", line 29, in inner
    out = fn(model, *args, **kwargs)
TypeError: TryOnImagenlite.sample() got an unexpected keyword argument 'person_images'
